apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devserverflavors.devserver.io
spec:
  group: devserver.io
  names:
    kind: DevServerFlavor
    listKind: DevServerFlavorList
    plural: devserverflavors
    singular: devserverflavor
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                default:
                  type: boolean
                defaultImage:
                  type: string
                resources:
                  type: object
                  properties:
                    requests:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    limits:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                nodeSelector:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                tolerations:
                  type: array
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                volumes:
                  type: array
                  items:
                    type: object
                    required: ["claimName", "mountPath"]
                    properties:
                      claimName:
                        type: string
                      mountPath:
                        type: string
                      readOnly:
                        type: boolean
            status:
              type: object
              properties:
                schedulable:
                  type: string
                  enum: ["AUTOSCALED", "Yes", "No", "Unknown"]
